/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mechanical-gear.glb --transform --types --output src/components/models/MechanicalGear.tsx 
Files: public/models/mechanical-gear.glb [19.59MB] > /home/gift/Documents/timex/src/components/models/mechanical-gear-transformed.glb [1.98MB] (90%)
Author: abdelghani.0 (https://sketchfab.com/abdelghani.0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-watch-mechanism-56e60ad7abf94f16a9dbf92f319ffdf7
Title: mechanical watch mechanism
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Spur_Gear005_gear_metalic_0: THREE.Mesh
    Spur_Gear001_gear_metalic_0: THREE.Mesh
    Spur_Gear_gear_metalic_0: THREE.Mesh
    Cylinder025_plastc_pink_0: THREE.Mesh
    Cube024_gear_metalic_0: THREE.Mesh
    Circle002_tiktok_0: THREE.Mesh
    escape_wheel_0001_escape_wheel001_0: THREE.Mesh
    Pallets_0001_ruby003_0: THREE.Mesh
    escapement_0001_escapement002_0: THREE.Mesh
    Balance_Axle_0001_axle002_0: THREE.Mesh
    Impulse_Pin_0001_ruby003_0: THREE.Mesh
    Balance_Wheel_0001_balance_wheel001_0: THREE.Mesh
    Cylinder026_scratch_0: THREE.Mesh
    Spur_Gear003_gear_metalic_0: THREE.Mesh
    Pin1_0_material_0: THREE.Mesh
    Cylinder028_Material003_0: THREE.Mesh
    Cylinder024_inside_metalblack_0: THREE.Mesh
    Cylinder021_plastc_pink_0: THREE.Mesh
    Cylinder008_inside_metalblack001_0: THREE.Mesh
    Cylinder001_black_watch_0: THREE.Mesh
    ['0']: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    scratch: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['inside_metal.black']: THREE.MeshStandardMaterial
    ['inside_metal.black.001']: THREE.MeshStandardMaterial
    black_watch: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/mechanical-gear-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Spur_Gear005" position={[25.412, -20.937, 132.269]} rotation={[-0.046, 0.002, -0.293]} scale={17.992}>
            <mesh name="Spur_Gear005_gear_metalic_0" geometry={nodes.Spur_Gear005_gear_metalic_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Spur_Gear001" position={[222.114, -77.782, 134.077]} rotation={[Math.PI, -0.015, -2.606]} scale={-18.388}>
            <mesh name="Spur_Gear001_gear_metalic_0" geometry={nodes.Spur_Gear001_gear_metalic_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Spur_Gear" position={[204.845, -190.742, 134.332]} rotation={[Math.PI, -0.015, 2.338]} scale={-18.93}>
            <mesh name="Spur_Gear_gear_metalic_0" geometry={nodes.Spur_Gear_gear_metalic_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube024" position={[191.718, 7.485, 137.106]} rotation={[0, 0.015, 1.516]} scale={100}>
            <group name="Cylinder025" position={[0.118, -0.178, -0.031]} rotation={[0, 0, -1.439]} scale={0.048}>
              <mesh name="Cylinder025_plastc_pink_0" geometry={nodes.Cylinder025_plastc_pink_0.geometry} material={materials.PaletteMaterial003} />
            </group>
            <mesh name="Cube024_gear_metalic_0" geometry={nodes.Cube024_gear_metalic_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Circle002" position={[111.225, -99.69, 152.321]} rotation={[3.129, -0.007, 3.132]} scale={-13.53}>
            <mesh name="Circle002_tiktok_0" geometry={nodes.Circle002_tiktok_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="escape_wheel_0001" position={[20.881, -251.526, 121.654]} rotation={[1.569, -0.72, 0.004]} scale={11.042}>
            <mesh name="escape_wheel_0001_escape_wheel001_0" geometry={nodes.escape_wheel_0001_escape_wheel001_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Pallets_0001" position={[9.678, -212.353, 130.952]} rotation={[-1.597, -1.211, 3.117]} scale={11.042}>
            <mesh name="Pallets_0001_ruby003_0" geometry={nodes.Pallets_0001_ruby003_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="escapement_0001" position={[9.678, -212.353, 130.952]} rotation={[-1.597, -1.211, 3.117]} scale={11.042}>
            <mesh name="escapement_0001_escapement002_0" geometry={nodes.escapement_0001_escapement002_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Balance_Axle_0001" position={[-5.543, -157.908, 128.441]} rotation={[-1.582, -1.171, 3.134]} scale={11.042}>
            <mesh name="Balance_Axle_0001_axle002_0" geometry={nodes.Balance_Axle_0001_axle002_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Impulse_Pin_0001" position={[-5.464, -158.042, 114.095]} rotation={[-1.574, 0.4, 3.138]} scale={11.042}>
            <mesh name="Impulse_Pin_0001_ruby003_0" geometry={nodes.Impulse_Pin_0001_ruby003_0.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Balance_Wheel_0001" position={[-5.481, -158.017, 112.426]} rotation={[-1.574, 0.416, 3.138]} scale={11.042}>
            <mesh name="Balance_Wheel_0001_balance_wheel001_0" geometry={nodes.Balance_Wheel_0001_balance_wheel001_0.geometry} material={materials.PaletteMaterial002} />
          </group>
        </group>
        <mesh name="Cylinder026_scratch_0" geometry={nodes.Cylinder026_scratch_0.geometry} material={materials.scratch} position={[-0.006, -1.576, 1.339]} rotation={[0, 0.015, 0]} scale={[0.26, 0.26, 0.063]} />
        <mesh name="Spur_Gear003_gear_metalic_0" geometry={nodes.Spur_Gear003_gear_metalic_0.geometry} material={materials.PaletteMaterial001} position={[1.148, -1.031, 1.317]} rotation={[0, 0.015, -0.014]} scale={0.187} />
        <mesh name="Pin1_0_material_0" geometry={nodes.Pin1_0_material_0.geometry} material={materials.PaletteMaterial002} position={[0.118, -1.815, 1.3]} rotation={[-1.536, -1.186, -3.114]} scale={0.109} />
        <mesh name="Cylinder028_Material003_0" geometry={nodes.Cylinder028_Material003_0.geometry} material={materials['Material.003']} position={[1.108, -0.997, 1.429]} rotation={[Math.PI, -0.015, 3.141]} scale={[-2.196, 2.196, 0.006]} />
        <mesh name="Cylinder024_inside_metalblack_0" geometry={nodes.Cylinder024_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[2.222, -0.778, 1.367]} rotation={[0, 0.015, 0.32]} scale={[0.128, 0.128, 0.007]} />
        <mesh name="Cylinder021_plastc_pink_0" geometry={nodes.Cylinder021_plastc_pink_0.geometry} material={materials.PaletteMaterial003} position={[0.998, -2.126, 1.371]} rotation={[0, 0.015, 0]} scale={0.035} />
        <mesh name="Cylinder008_inside_metalblack001_0" geometry={nodes.Cylinder008_inside_metalblack001_0.geometry} material={materials['inside_metal.black.001']} position={[-0.353, -0.531, 1.414]} rotation={[0, 0.015, 0]} scale={[0.061, 0.061, 0.003]} />
        <mesh name="Cylinder001_black_watch_0" geometry={nodes.Cylinder001_black_watch_0.geometry} material={materials.black_watch} position={[1.099, -0.997, 0.819]} rotation={[0, 0.015, 0]} scale={[2.129, 2.129, 0.255]} />
        <mesh name="0" geometry={nodes['0'].geometry} material={materials.PaletteMaterial002} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} position={[-0.049, -1.59, 1.066]} rotation={[-1.574, 0.424, 3.138]} scale={[110.424, 110.424, 110.423]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mechanical-gear-transformed.glb')
