/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/watch.glb --transform --types --output src/components/models/Watch.tsx 
Files: public/models/watch.glb [4.74MB] > /home/gift/Documents/timex/src/components/models/watch-transformed.glb [598.55KB] (87%)
Author: gorzi (https://sketchfab.com/gorzi90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/timex-expedition-watch-6afd4f17502e40739ec96cbdbece3237
Title: Timex Expedition Watch
*/

import * as THREE from 'three'
import React  from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useEffect } from 'react'
import type { JSX } from 'react'


type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_22: THREE.Mesh
    Object_25: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_40: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
    Object_56: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['indeksy.data']: THREE.MeshStandardMaterial
    indeksy: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    skora: THREE.MeshStandardMaterial
    ['skora.jasna']: THREE.MeshStandardMaterial
    ['indeksy.obrecz']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group | null>(null)
  const { nodes, materials, animations } = useGLTF('/models/watch-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const action = actions['Animation']
    if (!action) return

    action.setLoop(THREE.LoopRepeat, Infinity)
    action.reset().play()
  }, [actions])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode" position={[0, -1.518, 4.444]} rotation={[Math.PI / 2, 0, 0]}>
          <group name="Plane006_9" position={[-0.006, 2.251, 1.414]} rotation={[0, 1.243, 0]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Plane000_10" position={[0, 2.341, 0]}>
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Material} position={[0, -1.518, 5.082]} rotation={[Math.PI / 2, -0.522, 0]} scale={4.195}  />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} position={[-5.345, -11.37, 6.839]} rotation={[1.671, 0, 0]} scale={0.105} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['indeksy.data']} position={[-0.044, -1.499, 6.624]} rotation={[-Math.PI / 2, 1.055, 0]} scale={3.575} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.indeksy} position={[0, -1.518, 6.652]} rotation={[Math.PI / 2, 0, 0]} scale={3.575} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial002} position={[0, -1.518, 7.11]} rotation={[Math.PI / 2, 0, 0]} scale={3.321} />
        <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.PaletteMaterial003} position={[-0.203, -11.133, 1.283]} rotation={[0.101, 0, 0]} scale={[5.68, 3.468, 5.525]} />
        <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.skora} position={[0, -7.304, 7.326]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials['skora.jasna']} position={[0, -7.304, 7.326]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['indeksy.obrecz']} position={[0, -1.518, 6.876]} rotation={[Math.PI / 2, 0, 0]} scale={1.003} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/watch-transformed.glb')
